Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Max: 26
Metrics/CyclomaticComplexity:
  Max: 11
Metrics/MethodLength:
  Max: 25
